In this demo, we demonstrate how to use the MaxEnt_Reg script. We will be going over how to do the following:

1. Reading in the MaxEnt data and constraint information
2. Running the model using different gradient descent techniques (without regularization)
3. How to add regularization 
    * Target prior ```TGTPrior``` 
    * Difference prior ```DIFPrior```

In [1]:
## Good old NumPy
import numpy as np

## Specialized classes
from utils.MaxEnt import MaxEnt
from utils.Regularization import TGTPrior, DIFPrior

## Utility function for reading in constraint and data information
from utils.OTSoft_file_reader import get_info


For this demonstration, we will be looking at the Hayes Pseudo-Korean data

In [2]:
## Read in data and constraint information
constraint_names, underlying_forms, candidates, violations, observed_probs = get_info(
    "toy_datasets/HayesPseudoKorean-RichBase.txt"
)

## Print basic information
print(f"Constraint names:")
[print(cn) for cn in constraint_names]
print()

## Initialize a MaxEnt object
me = MaxEnt(constraint_names)

## Print initial weights to commandline
print("Initial weights:")
print(me.cws)


Constraint names:
Ident (asp)
Ident (voice)
Ident (asp)/_V
Ident (voice)/_V
*[+v][-v][+v]
*dh
*[-son/+voice]
*aspiration

Initial weights:
[[2.36380107]
 [5.48127113]
 [6.5108408 ]
 [0.68091117]
 [1.39091299]
 [1.31031094]
 [9.20953316]
 [2.31205001]]


In [3]:
## Perform learning without regularization and returns the final weights
new_weights, learning_history = me.SGD_learn(violations=violations, observed_prob=observed_probs)

print("Weights after learning:")
print(new_weights)
print()

Weights after learning:
[[2.71989246]
 [7.10322867]
 [6.60593825]
 [2.30285335]
 [3.01283685]
 [1.31040357]
 [7.58762799]
 [2.47908691]]



In [4]:
## M >> F
cns = constraint_names
grs = [
    ["Ident (asp)", "Ident (voice)", "Ident (asp)/_V", "Ident (voice)/_V"], 
    ["*[+v][-v][+v]", "*dh", "*[-son/+voice]","*aspiration"]
]
mus = [1, 10]
sms = [1, 1]
target_prior = TGTPrior(cns, grs, mus, sms)

## Perform learning with regularization and returns the final weights
new_weights, learning_history = me.SGD_learn(violations, observed_probs, 1, 10000, 0.05, target_prior)

print("Weights after learning:")
print(new_weights)
print()

Weights after learning:
[[ 1.72752082]
 [ 1.05639917]
 [ 1.72751643]
 [ 1.05639502]
 [10.00461807]
 [10.        ]
 [ 9.99539051]
 [ 9.27249012]]



In [5]:
## M >> F TGT
cns = constraint_names
grs = [
    ["Ident (asp)", "Ident (voice)", "Ident (asp)/_V", "Ident (voice)/_V"], 
    ["*[+v][-v][+v]", "*dh", "*[-son/+voice]","*aspiration"]
]
mus = [1, 10]
sms = [1, 1]
target_prior = TGTPrior(cns, grs, mus, sms)

## Perform learning with regularization and returns the final weights
new_weights, learning_history = me.SGD_learn(violations, observed_probs, 1, 10000, 0.05, target_prior)

print("Weights after learning:")
print(new_weights)
print()

Weights after learning:
[[ 1.64473262]
 [ 1.05793692]
 [ 1.64472839]
 [ 1.05793287]
 [10.01228657]
 [10.        ]
 [ 9.98772151]
 [ 9.35527792]]



In [6]:
## M >> F DIF
cns = constraint_names
grs = [
    ["Ident (asp)", "Ident (voice)", "Ident (asp)/_V", "Ident (voice)/_V"], 
    ["*[+v][-v][+v]", "*dh", "*[-son/+voice]","*aspiration"]
]
mus = [5]
sms = [3]
msg = [[0, 1]]
diff_prior = DIFPrior(cns, grs, mus, sms, msg)

## Perform learning with regularization and returns the final weights
new_weights, learning_history = me.SGD_learn(violations, observed_probs, 1, 10000, 0.05, diff_prior)

print("Weights after learning:")
print(new_weights)
print()

Weights after learning:
[[2.78559214]
 [7.1322933 ]
 [6.68752525]
 [2.33191916]
 [2.80054785]
 [1.18972812]
 [7.55855812]
 [2.38141616]]



In [7]:
## M >> F DIF
cns = constraint_names
grs = [
    ["Ident (asp)"], 
    ["Ident (voice)"], 
    ["Ident (asp)/_V"], 
    ["Ident (voice)/_V"], 
    ["*[+v][-v][+v]", "*dh", "*[-son/+voice]", "*aspiration"]
]
mus = [3, 3, 3, 5]
sms = [1, 1, 1, 3]
msg = [[0, 1], [1, 2], [2, 3], [3, 4]]
diff_prior = DIFPrior(cns, grs, mus, sms, msg)

## Perform learning with regularization and returns the final weights
new_weights, learning_history = me.SGD_learn(violations, observed_probs, 1, 10000, 0.05, diff_prior)

print("Weights after learning:")
print(new_weights)
print()

Weights after learning:
[[13.78436011]
 [10.78980268]
 [ 7.80054205]
 [ 4.81631599]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.        ]]

